### ISSUE TITLE
spectrum not showing for all detections

### ISSUE THREAD

**Issue by rs-tamar** [RespirationScan/issues#10]

**Comment by gilzimmerman** [comment]
@rs-tamar I managed to resolve the issue you were seeing with compiling the PBIT. 

I reimplemented the changes you made (such that the tables are now set to import). This does seem to resolve the performance issues (at the expense of memory). 

Please pull, review, and request a pull into dev.

**Comment by rs-tamar** [comment]
This issue has now been resolved (as shown in our session) that required switching to the JSON format in order to use the embedded data feature that solved the Spectrum Graph issue above
