### ISSUE TITLE
make spectrum bar width identical

### ISSUE THREAD

**Issue by gilzimmerman** [RespirationScan/issues#14]
The width of the bars in the spectrum graph should be the same for every molecule.

Furthermore, the axes should be fixed:

x-axis: 0 to 650
yaxis: 0 to 1000 (or 100, whichever is max)

**Comment by rs-tamar** [comment]
I just double-check this situation with our source data and max x is 599 but max y rightly or wrong is 46,198,507. currently, I have limited it to 1,000 but if you're hovering over the chart you will get the real number behind

**Comment by rs-tamar** [comment]
A new version related to this issue has been released for you to check and review

**Comment by gilzimmerman** [comment]
> I just double-check this situation with our source data and max x is 599 but max y rightly or wrong is 46,198,507. currently, I have limited it to 1,000 but if you're hovering over the chart you will get the real number behind

Yeah, I see. This is because of errors in the RS-01 dataset. In this case, we should make the max of the y-axis dynamic, not fixed. 

Clicking on different spectra will still show different widths of the bars. Let's continue to work on this.

**Comment by rs-tamar** [comment]
I now amend the Y axis back to Auto mode

**Comment by rs-tamar** [comment]
I have now released a new version, where I have replaced the Spectrum graph object with a new pro version from pbivizedit.com, this seems to improve the visibility of the columns with a really good zoom option, but it also has a few differences, for example, it doesn't have the option to present the compound id as a title

**Comment by gilzimmerman** [comment]
closed by using charticulator option.

possible other options to consider in the future include: 
- python visualization (requires further cosmetic tweaking) 
- pbi custom visualization (great zoom and interactivity, lacks grouping by compound_id and transferring with pbi-tools)
