### ISSUE TITLE
counters

### ISSUE THREAD

**Issue by gilzimmerman** [RespirationScan/issues#3]
per Igal's request.

**Comment by gilzimmerman** [comment]
I will go into further detail once Igal provides more information.

**Comment by gilzimmerman** [comment]
These are the requests for the counters. Some definitions:

Molecules = each different molecule name that appears
Appearance = number of detections in CEF = total dots in top-right graph
Runs = number of measurements selected


For every click, they would like to see the number of molecule names, the total dots in the top right graph, and the number of measurements it came from. A counter box might look like:

mol 2
app 5
run 1

That would mean that two different molecules were selected, they have a total of 5 appearances in the CEF file, and it came from one single measurement.

in our language that would be: count(molecule_names), count(retention_time), count(measurement)

**Comment by rs-tamar** [comment]
In total, we now have three counters that represent Appearance,  Molecules and Runs

**Comment by gilzimmerman** [comment]
Complete! Great work, just waiting to merge into dev.
