### ISSUE TITLE
filter by probabilty

### ISSUE THREAD

**Issue by gilzimmerman** [RespirationScan/issues#8]
Ability to filter all data by probability

**Comment by gilzimmerman** [comment]
probabilities are available in the dataset

need to add visual filter for probability range
default low: 0
default high: 100

should accommodate decimal digits same as the data

**Comment by rs-tamar** [comment]
A new version has been pushed as required

**Comment by gilzimmerman** [comment]
filter works really well, but a new problem has been introduced: 

cannot show the spectrum of any molecule. 

Example: 

Patient 608, Acetone, Tube 5, Filter setting 90-100, all points on top-left graph deselected, select any point on top-right graph - spectrum graph (bottom right) does not change.

(edit: forgot to include Acetone as selected molecule)

**Comment by rs-tamar** [comment]
Here is the message behind this issue

<img width="526" alt="image" src="https://github.com/RespirationScan/issues/assets/113028257/a27441fe-84f4-4d23-8b2b-e325a8ddea21">

**Comment by rs-tamar** [comment]
Again, this seems to happen every time we hit the product limit, however, if you restrict the search a bit more it will return to show 

<img width="953" alt="image" src="https://github.com/RespirationScan/issues/assets/113028257/ea4743e3-949f-4859-b59b-920ebe277083">

**Comment by gilzimmerman** [comment]
You were able to resolve this before we released MS1 - it was not an issue then. 
I think some slicer we added or some change we made since has reintroduced this problem. 

Selecting a single dot on the top-right plot should limit the data set to exactly 1 spectrum, certainly not to many data points to display.

I suspect a slicer we added or a reconfiguration is changing what the plot is attempting to display now. 

We need to figure it out.

**Comment by rs-tamar** [comment]
Hi Gil, I now release a new version that includes the following modification 
1. Bug Fix:  select any point on the top-right graph - the spectrum graph (bottom right) does not change.
2. Add Molecule Type and Position to Category (I think it just makes sense, but if you don't like it we can take it off)
3. add Counter, represent the number of compounds behind the categories combined 
3. improve visibility

**Comment by gilzimmerman** [comment]
Resolved and pushed into dev on commit 9878aa8
